### ISSUE TITLE
Add channels

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/whisper#1]
Each Room can have many channels

**Comment by Alir3z4** [comment]
@AmirSavand do you think we should implement such thing at all ?
I mean since we can create as many room as we want, does creating Channels makes sense any more ?

**Comment by AmirSavand** [comment]
I thought this is channels as in django channels.
Not at all, rooms are the same as channels.

**Comment by AmirSavand** [comment]
We can easily rename rooms to channels (front-end only).

**Comment by Alir3z4** [comment]
Exactly.
I'm happy to close this <3
