### ISSUE TITLE
List of users in a room

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/whisper#11]

**Comment by Alir3z4** [comment]
This should come via the websocket itself.
Will make it happen

**Comment by Alir3z4** [comment]
Ok, let's do this via the websocket.
This is going to be fun!

**Comment by Alir3z4** [comment]
Ok, this is way complicated that I thought.
I need a way to keep track of active connections.

Resource: 
* https://github.com/django/channels/issues/293
* https://github.com/unhangout/django-channels-presence
* https://github.com/ploggingdev/djangochat

**Comment by AmirSavand** [comment]
Find a way! Good luck!

**Comment by Alir3z4** [comment]
Pull request #32 is there to make this happen.
The command "room_users" is what you're looking for.

Pass `{"command": "room_users", "room": roomId}`
and it will respond back with 


https://github.com/SavandBros/whisper/blob/f416fd472750eb6c0948a9a2004873e125abb15e/chat/tests/test_chat_consumer.py#L83-L91

**Comment by Alir3z4** [comment]
Cool.
I need to make some changes before merging it in.
