### ISSUE TITLE
Theme color (primary)

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/whisper#16]
Although, user will be able to change theme color for himself but our global primary color should be decided now.

Awesome color palettes: https://flatuicolors.com

![image](https://user-images.githubusercontent.com/4629328/40313751-83f715a6-5d27-11e8-92cb-80931c4857b1.png)

**Comment by AmirSavand** [comment]
@Alir3z4 check the colors and give me some options.

**Comment by Alir3z4** [comment]
can't open that address.
Also you know I'm such a color blind :D

Choose something that doesn't hurt eyes and can have the text readable easily.

**Comment by AmirSavand** [comment]
Cool

**Comment by AmirSavand** [comment]
You can check em from here and give me a name:

![image](https://user-images.githubusercontent.com/4629328/40313736-7bd85308-5d27-11e8-9214-494ba6a7b51a.png)

**Comment by Alir3z4** [comment]
midnight blue, what do you think ?

**Comment by AmirSavand** [comment]
That's cool, I totally missed your reply.

**Comment by AmirSavand** [comment]
Note that user can change the color but midnight blue will be the default color.

**Comment by Alir3z4** [comment]
Excellent, that works fine
