### ISSUE TITLE
Get messages of rooms that you're not currently viewing

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/whisper#28]
@Alir3z4 do you like this?

**Comment by AmirSavand** [comment]
Yes joined and not viewing.
It's easy, check this out you'll know how I do it: https://github.com/SavandBros/whisper/blob/master/static/assets/app.js#L33

**Comment by AmirSavand** [comment]
Each `Message` instance is inside `Room.messages` and I only show the room user has selected.

If you select a room that you're not joined in yet, you will join (`Room.join()`)

**Comment by Alir3z4** [comment]
Just saw the code, the code is great.
Awesome work <3
