### ISSUE TITLE
Login and sign up ignore our template

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/whisper#43]

**Comment by Alir3z4** [comment]
Have a look at [django-allauth](https://readthedocs.org/projects/django-allauth/) to find out how to override the login page, I am sure it has a way to do so.

Let me know if you were not able to.

**Comment by AmirSavand** [comment]
I did override it in `urls.py` but it just didn't work.
I will try again but there are many ways to do this, I'd want you to choose the best way.

**Comment by Alir3z4** [comment]
No, you shouldn't touch the URLs at all.
You only need to create a template in account/login.html and it will do the trick.

https://django-allauth.readthedocs.io/en/stable/templates.html#overridable-templates

**Comment by AmirSavand** [comment]
Yes that's what I did but in `registration/`, I will try `account/` too.
