### ISSUE TITLE
Many alerts in admin

### ISSUE THREAD

**Issue by AmirSavand** [SavandBros/whisper#44]
After doing changes to profile, when I visit admin, I see these:

![image](https://user-images.githubusercontent.com/4629328/40498698-c56dd824-5f90-11e8-8d06-80b98294ce04.png)

**Comment by Alir3z4** [comment]
Let me check this quick

**Comment by AmirSavand** [comment]
This is no issue but a weird behavior, first time I noticed this about django admin.

**Comment by Alir3z4** [comment]
Do you get these always ?
They shouldn't be permanent and should go away once you see them.
This can be closed.
feel free to reopen if it becomes critical :D

**Comment by AmirSavand** [comment]
Yea they are gone after refresh, I only see them after logging in.
