### ISSUE TITLE
Setup email sending

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/whisper#46]

**Comment by AmirSavand** [comment]
Will we be using `.txt` as email templates?

**Comment by AmirSavand** [comment]
Why would someone use a fake phone number? They will lose all their stuff when they want to change phone, password, etc..

**Comment by Alir3z4** [comment]
Someone wanting to mess up with things.

However since this is going to be used internally I don't think that would
be a problem.

Although everything that can go wrong will go wrong.

**Comment by AmirSavand** [comment]
The fake phone numbers receive notifications too? Like the fake emails?
