### ISSUE TITLE
Support Markdown via angular-marked

### ISSUE THREAD

**Issue by Alir3z4** [SavandBros/whisper#49]
This is also very useful.
Frontend can take care of this part.

via https://github.com/Hypercubed/angular-marked

**Comment by AmirSavand** [comment]
Yes, this is good.

**Comment by Alir3z4** [comment]
Nice!

**Comment by AmirSavand** [comment]
`ngEmbed` and `angular-markdown` both support syntax highlighting.

I have to check and disable one.

**Comment by Alir3z4** [comment]
Let's first start using angular-marked then we add ngEmbed.
At least with marked we get tons of stuff out of the box

**Comment by AmirSavand** [comment]
I don't think we'd need this in any way, shape or form.

Reopen if you disagree.

**Comment by Alir3z4** [comment]
Fine, that's ok with me
